### PR TITLE
Enrich the Installation description of README

### PR DESCRIPTION
**Pull request by YukiMatsumura**
Chore, README update.

Installation section in README.md was not described add JitPack repository and apply plugin.

Please confirm :)

### CODE REVIEW

**Comment by hotchemi** [comment]
LGTM! Btw why not upload to the jcenter @rejasupotaro ?

**Comment by rejasupotaro** [comment]
Thank you for your PR! LGTM :wine_glass: 

> why not upload to the jcenter @rejasupotaro ?

Actually, this library was published on jcenter until version 1.x. But maintaining libraries on jcenter was a little bit painful for me. Then, I moved to jitpack and I'm publishing my libraries using jitpack. If there is a strong requirement, I will bring back the code.

**Comment by hotchemi** [comment]
Sorry for the late, actually I plan to use it in production. We don't use jitpack so could you re-upload to jcenter again?

**Comment by rejasupotaro** [comment]
@hotchemi A strong requirement came! Okay, I can work on it tomorrow. Can you wait?

**Comment by hotchemi** [comment]
Sure, sure. We're not hurrying :coffee:

**Pull request merged**
