### PR TITLE
Generate initialize methods in compile time

### PR DESCRIPTION
**Pull request by rejasupotaro**
Related to https://github.com/rejasupotaro/kvs-schema/issues/10, I started generating initialize methods in compile time to reduce boiler plate.
Generate class would be like below.

```java
// ExamplePrefs.java
...

private static ExamplePrefs singleton;

public static ExamplePrefs get(Context context) {
  if (singleton != null) return singleton;
  synchronized (ExamplePrefs.class) { if (singleton == null) singleton = new ExamplePrefs(context); };
  return singleton;
}
```

### CODE REVIEW

**Comment by hotchemi** [comment]
@rejasupotaro Why did u delete the test class?

**Comment by rejasupotaro** [comment]
We should not write tests for generated text... should be written for the behaviour.

**Comment by hotchemi** [comment]
Umm, I think you should. Because you might miss the breaking from other guys pull request.
But it's your code so I respect your opinion.

**Comment by rejasupotaro** [comment]
@hotchemi We agree on that point. We should focus on how to avoid bugs.

- Checking text equality.
 - Can see how generated code is changed.
 - Doesn't prove the correctness.
 - Needs to update every time we change `SchemaWriter`.
- Adding behavioural tests.
 - Can write tests for all interfaces.
 - Easy to maintain.
 - Helps us to find bugs https://github.com/rejasupotaro/kvs-schema/pull/13

I think writing behavioural tests would be enough. Don't you think it is enough? :confused:

**Comment by hotchemi** [comment]
OK. in this case, it's so easy to test on the Android JUnit. Make sense :+1: Have both test is the best but it's depends on the situation.

**Comment by rejasupotaro** [comment]
> but it's depends on the situation.

I agree. Thank you for sharing your thoughts :+1:

**Pull request merged**
